name: Python Flask App

on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]
  workflow_dispatch:

env:
  FLASK_APP: app.py
  FLASK_ENV: development
  ARTIFACT_NAME: customer-app
  WORKSPACE_ENVIRONMENT_VARIABLE: 'custom workspace environment variable for all jobs'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            #- name: Lint with flake8
            #  run: |
                  # stop the build if there are Python syntax errors or undefined names
            #      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            #      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Test with pytest
              run: |
                  pythonPath=`which python3`
                  echo "Python Path $pythonPath"
                  echo "Current Directory ${{ github.workspace }}"
                  echo "FLASK_APP ${{ env.FLASK_APP }}"
            #      $pythonPath ${{ github.workspace }}/${{ env.FLASK_APP }}
            - name: Get Organization Name
              run: |
                  echo ${{ github.repository_owner }}
            - name: Check out the repo
              uses: actions/checkout@v2
              with:
                  # Disabling shallow clone is recommended for improving relevancy of reporting
                  # fetch-depth: 0
                  repository:  ${{ github.repository_owner }}/spring-cars
                  ref: devops
                  path: test.txt
            - name: List files
              run: |
                  ls -la
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.ARTIFACT_NAME }}
                  path: .
    deploy:
      runs-on: syr-org-v1
      needs: build
      steps:
        - name: Upload artifact
          uses: actions/download-artifact@v2
          with:
              name: ${{ env.ARTIFACT_NAME }}
              path: ${{ github.workspace }}
    windows:
      env:
        JOB_ENVIRONMENT_VARIABLE: 'custom job environment variable for windows'
      runs-on: windows-latest
      steps:
        - name: Print custom environment variables from windows-latest
          env:
            STEP_ENVIRONMENT_VARIABLE: 'custom step environment variable for powershell'
          run: |
            echo "Accessing environment variables in run command"
            echo "$Env:WORKSPACE_ENVIRONMENT_VARIABLE"
            echo "$Env:JOB_ENVIRONMENT_VARIABLE"
            echo "$Env:STEP_ENVIRONMENT_VARIABLE"
            echo "------------------------------------------------------"
            echo "Accessing environment variables using env context"
            echo "${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
            echo "${{ env.JOB_ENVIRONMENT_VARIABLE }}"
            echo "${{ env.STEP_ENVIRONMENT_VARIABLE }} Not defined"

    #commit-and-push:
    #  runs-on: syr-org-v1
    #  needs: build
    #  steps:
    #    - name: "Checkout"
    #      uses: actions/checkout@v2
    #    - name: "Commit and push changes"
    #    #  env:
    #    #    ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
    #      run: |
    #        date > generated.txt
    #        git config user.name Syr7-s
    #        git config user.email isa.sayar1725@gmail.com
    #        git add .
    #        git commit -m "generated"
    #        git push